version: "3.8"

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: momentum-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust-backend
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - momentum-network

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: momentum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - momentum-network

  # Backend application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momentum-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rust-backend
      REDIS_URL: redis://redis:6379/
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      RUST_LOG: ${RUST_LOG:-info}
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - momentum-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  momentum-network:
    driver: bridge
