[advisories]
# validator 0.18.1 使用 idna 0.5.0，存在已知漏洞
# 等待 validator 更新到支持 idna 1.0+ 的版本
# 风险评估：此漏洞影响 Punycode 解码，对本项目影响较小
ignore = [
    "RUSTSEC-2024-0421",  # idna: accepts Punycode labels issue
]

# 允许未维护的依赖警告（proc-macro-error 等）
informational_warnings = ["unmaintained"]
